# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('fruit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fusion.Fruit')),
            ],
            bases=('fusion.fruit',),
        ),
        migrations.CreateModel(
            name='Membrillo',
            fields=[
                ('fruit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fusion.Fruit')),
            ],
            bases=('fusion.fruit',),
        ),
        migrations.CreateModel(
            name='Pineapple',
            fields=[
                ('fruit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fusion.Fruit')),
            ],
            bases=('fusion.fruit',),
        ),
        migrations.AddField(
            model_name='fusion',
            name='left_hand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_left_hands', to='fusion.Fruit'),
        ),
        migrations.AddField(
            model_name='fusion',
            name='right_hand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_right_hands', to='fusion.Pen'),
        ),
    ]
